# -*- encoding: utf-8 -*-
from . import test_asset_lifecycle
from . import test_asset_revalue_dispose
from . import test_deferred_recognition
from . import test_lease_lifecycle
from . import test_lease_modify_terminate
from . import test_cron_post_due
from . import test_performance
from . import test_multi_book
from . import test_components_impairment_lvp
from . import test_lvp_fiscal_migration
from . import test_ias36_cgu
from . import test_auc
from . import test_asset_autocreate
from . import test_prorata_mode
from . import test_freeze_after_post
from . import test_asset_reports
from . import test_golden_ias36
from . import test_golden_ias38
from . import test_golden_ifrs16
from . import test_golden_ifrs16_remeasure
from . import test_property_ifrs16
from . import test_workflow_guard
from . import test_double_post_guard
from . import test_currency_integrity
from . import test_tour
from . import test_partner_statistics
from . import test_remediation_159
