# -*- coding: utf-8 -*-
{
    'name': "Zilancer Customisation",
    'version': '19.0.1.0.12',
    "category": 'Contacts',
    'summary': """Zilancer Customisation""",
    'description': """Zilancer Customisation""",
    'author': 'Zilancer',
    'company': 'Zilancer',
    'maintainer': 'Zilancer',
    'website': 'https://www.zilancer.com',
    'depends': ['mail', 'contacts', 'sale', 'sale_stock', 'sale_purchase_inter_company_rules', 'project', 'helpdesk_mgmt', 'print_minutes_of_meeting', 'link_tracker', 'event', 'sale_order_enquiry', 'mrp', 'purchase'],
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_sequence.xml',
        'views/stock_picking_views.xml',
        'views/sale_order_view.xml',
        'views/purchase_order_views.xml',
        'views/mrp_production_views.xml',
        'views/res_users_views.xml',
        'views/crm_lead_views.xml',
        'views/product_views.xml',
        'views/analysis_masters_views.xml',
        'views/res_partner_views.xml',
        'views/helpdesk_ticket_view.xml',
        'views/calendar_event_view.xml',
        'views/event_event_view.xml',
        'views/sales_person_dashboard_view.xml',
        'views/res_company_views.xml',
        'views/product_category_views.xml',
        'views/account_move_views.xml',
        'reports/ir_actions_report.xml',
        'reports/ir_actions_report_templates.xml',
        'reports/non_tax_green_report.xml',
        'reports/tax_blue_report.xml',
        'reports/tax_green_report.xml',
        'reports/auto_pro_forma_report.xml',
        'reports/aviation_report.xml',
        'reports/without_tax_quote_report.xml',
        'reports/delivery_slip_report.xml',
        'reports/toll_blanding_report.xml',
        'reports/pgm_lube_eu_report.xml',
        'reports/pgm_oman_report.xml',
        'reports/pgm_singapore_report.xml',
        'reports/pgm_greece_report.xml',
        'wizard/sale_order_approval_views.xml',
        'wizard/sale_amendment_wizard_views.xml',
    ],
    'images': ['static/description/banner.png'],
    'assets': {
        'web.assets_backend': [
            'zilancer_customisation/static/src/css/dynamic_dashboard.css',
            'zilancer_customisation/static/src/js/datetime_field_format.js',
            'zilancer_customisation/static/src/js/datetime_field_format.xml',
        ],
    },
    'license': "LGPL-3",
    'installable': True,
    'auto_install': False,
    'application': False
}
